server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 131171
    url: jdbc:mariadb://localhost:3306/backup_baf
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true